### ISSUE TITLE
Is documentation out of date

### ISSUE THREAD

**Issue by zxkane** [jekyll/docker#85]
I am trying to build a for of Jekyll image due to this container will install gems from Internet when I run the container. However the rubygems.global.ssl.fastly.net was blocked in my network, I would to use a mirror of it in my fork container.

I'm following the guide in README to build Jekyll image. However I failed to build this image in both Mac OSX and Ubuntu.

In mac, it always said `excon` is not installed even though it already was installed.

> ➜  docker git:(master) bundle install                    
> Using excon 0.45.4
> Using json 1.8.3
> Using docker-api 1.26.0
> Using forwardable-extended 2.4.2
> Using pathutil 0.3.0
> Using simple-ansi 1.0.2
> Using docker-template 0.2.0 from git://github.com/envygeeks/docker-template.git (at master)
> Using bundler 1.9.7
> Bundle complete! 1 Gemfile dependency, 8 gems now installed.
> Use `bundle show [gemname]` to see where a bundled gem is installed.
> ➜  docker git:(master) 
> ➜  docker git:(master) 
> ➜  docker git:(master) bundle exec docker-template jekyll
> Could not find excon-0.45.4 in any of the sources
> Run `bundle install` to install missing gems. 

In ubuntu 14.04, I got below script error.

> ➜  docker git:(master) ✗ bundle install
> Using excon (0.45.4) 
> Using json (1.8.3) 
> Using docker-api (1.26.0) 
> Using forwardable-extended (2.4.2) 
> Using pathutil (0.3.0) 
> Using simple-ansi (1.0.2) 
> Using docker-template (0.2.0) from git://github.com/envygeeks/docker-template.git (at master) Enter your password to install the bundled RubyGems to your system: 
> 
> Using bundler (1.3.5) 
> Your bundle is complete!
> Use `bundle show [gemname]` to see where a bundled gem is installed.
> ➜  docker git:(master) ✗ 
> ➜  docker git:(master) ✗ 
> ➜  docker git:(master) ✗ bundle show   
> Gems included by the bundle:
>   * bundler (1.3.5)
>   * docker-api (1.26.0)
>   * docker-template (0.2.0 841e387)
>   * excon (0.45.4)
>   * forwardable-extended (2.4.2)
>   * json (1.8.3)
>   * pathutil (0.3.0)
>   * simple-ansi (1.0.2)
> ➜  docker git:(master) ✗ bundle exec docker-template jekyll
> /home/zxkane/.bundler/ruby/1.9.1/docker-template-841e387e48e7/bin/docker-template:6:in `<top (required)>': undefined local variable or method `__dir__' for main:Object (NameError)
>    from /var/lib/gems/1.9.1/bin/docker-template:23:in `load'
>    from /var/lib/gems/1.9.1/bin/docker-template:23:in `<main>'

Any suggestion for it.

Thank you.

**Comment by envygeeks** [comment]
Docker-Template (https://github.com/envygeeks/docker-template) only supports Ruby 2.1+, however, it works on 2.0+ more than likely as it was tested on that up until just a few days ago when it was dropped since 2.0 is EOL.

Neither this project nor it's upstream projects support EOL Rubies.
